version: '2'

services:

  ### CONTAINERS COMPARTILHADOS ENTRE OS AMBIENTES DE TESTE ###
  smtp:
    image: guilhermeadc/sei3_mailcatcher:7.2
    ports:
      - "1080:1080"

  memcached:
    image: guilhermeadc/sei3_memcached:7.2
    ports:
      - "11211:11211"

  proxy:
    image: diouxx/apache-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./assets/proxy:/opt/proxy-conf
    links:
      - org1-http:org1-http
      - org2-http:org2-http

  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    links:
      - proxy:org1-http
      - proxy:org2-http
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
      - ./assets/arquivos/test_files_index.txt:/test_files_index.txt
      - /tmp:/tmp

  php-test-functional:
    image: processoeletronico/vagrant_sei4_httpd
    container_name: php-test-functional
    depends_on:
      - org1-database
      - org2-database
      - selenium
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./assets/config:/opt/sei/config/mod-pen
      - .:/tests
      - /tmp:/tmp
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9000 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - CONTEXTO_ORGAO_A_DB_SEI_DSN=${CONTEXTO_ORGAO_A_DB_SEI_DSN}
      - CONTEXTO_ORGAO_B_DB_SEI_DSN=${CONTEXTO_ORGAO_B_DB_SEI_DSN}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - ORG1_CERTIFICADO=${ORG1_CERTIFICADO}
      - ORG1_CERTIFICADO_SENHA=${ORG1_CERTIFICADO_SENHA}
      - ORG2_CERTIFICADO=${ORG2_CERTIFICADO}
      - ORG2_CERTIFICADO_SENHA=${ORG2_CERTIFICADO_SENHA}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - org1-database:${ORG1_DATABASE_HOST}
      - org2-database:${ORG1_DATABASE_HOST}
      - selenium:selenium
    command: "true"

  ### CONTAINERS DO AMBIENTE DO ÓRGÃO 1 ###

  org1-database:
    image: ${ORG1_DATABASE_IMAGE}:7.2
    container_name: org1-${ORG1_DATABASE_NAME}
    ports:
      - "${ORG1_DATABASE_HOST_PORT}:${ORG1_DATABASE_GUEST_PORT}"

  org1-http:
    image: guilhermeadc/sei3_httpd-2.4:7.2
    container_name: org1-http
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ./assets/cron.d:/etc/cron.d
      - ./assets/config:/opt/sei/config/mod-pen
      - ../../src/scripts:/opt/sei/scripts/mod-pen
      - ../../src/scripts:/opt/sip/scripts/mod-pen
      - ../../src/bin:/opt/sei/bin/mod-pen
      - ../../src:/opt/sei/web/modulos/pen
      - ./assets/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./assets/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
    environment:
      - SEI_HOST_URL=http://${ORG1_HOSTNAME}
      - CERTIFICADO=${ORG1_CERTIFICADO}
      - CERTIFICADO_SENHA=${ORG1_CERTIFICADO_SENHA}
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9000 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - memcached:memcached
      - smtp:smtp
      - org1-database:${ORG1_DATABASE_NAME}

  ### CONTAINERS DO AMBIENTE DO ÓRGÃO 2 ###

  org2-database:
    image: ${ORG2_DATABASE_IMAGE}:7.2
    container_name: org2-${ORG2_DATABASE_NAME}
    ports:
      - "${ORG2_DATABASE_HOST_PORT}:${ORG2_DATABASE_GUEST_PORT}"

  org2-http:
    image: guilhermeadc/sei3_httpd-2.4:7.2
    container_name: org2-http
    volumes:
      - ${SEI_PATH}/sei:/opt/sei
      - ${SEI_PATH}/sip:/opt/sip
      - ${SEI_PATH}/infra:/opt/infra
      - ../../src/scripts:/opt/sei/scripts/mod-pen
      - ../../src/scripts:/opt/sip/scripts/mod-pen
      - ../../src/bin:/opt/sei/bin/mod-pen
      - ../../src:/opt/sei/web/modulos/pen
      - ./assets/config:/opt/sei/config/mod-pen
      - ./assets/cron.d:/etc/cron.d
      - ./assets/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./assets/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
    environment:
      - SEI_HOST_URL=http://${ORG2_HOSTNAME}
      - CERTIFICADO=${ORG2_CERTIFICADO}
      - CERTIFICADO_SENHA=${ORG2_CERTIFICADO_SENHA}
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9000 start_with_request=0
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - memcached:memcached
      - smtp:smtp
      - org2-database:${ORG2_DATABASE_NAME}
